apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:latest
          ports:
            - containerPort: 7050
        - name: peer
          image: hyperledger/fabric-peer:latest
          ports:
            - containerPort: 7051
