apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  selector:
    app: blockchain
  ports:
    - protocol: TCP
      port: 7050
      targetPort: 7050
    - protocol: TCP
      port: 7051
      targetPort: 7051
  type: LoadBalancer
